package fr.uga.l3miage.pc.prisonersdilemma.enums;

public enum TypeStrategy {
    DEFAULT,
    DONNANT_DONNANT,
    DONNANT_DONNANT_ALEATOIRE,
    DONNANT_POUR_DEUX_DONNANTS_ALEATOIRE,
    DONNANT_POUR_DEUX_DONNANTS,
    SONDEUR_NAIF,
    SONDEUR_REPENTANT,
    PACIFICATEUR_NAIF,
    VRAI_PACIFICATEUR,
    ALEATOIRE,
    TOUJOURS_TRAHIR,
    TOUJOURS_COOPERER,
    RANCUNIER,
    PAVLOV,
    PAVLOV_ALEATOIRE,
    ADAPTATIVE,
    GRADUEL,
    DONNANT_DONNANT_SOUPCONNEUX,
    RANCUNIER_DOUX
}
